### ISSUE TITLE
refactor: workflow restart/rerun using the same workspace

### ISSUE THREAD

**Issue by roksys** [reanahub/reana-workflow-controller#289]
- Refactor workflow restart/rerun using the same workspace as a new run, which will help for future accounting. 
- Save workspace path in workflow model, will help for future EOS workspaces.

**Comment by diegodelemos** [comment]
LGTM code-wise, just testing it out remaining

**Comment by tiborsimko** [comment]
Remains to be done:

(1) separate restart command so that workflow spec changes can be taken into account:

```
$ reana-client restart -f reana.yaml -w myanalysis.42
```

(2) consider whether to (2a) keep run_number as DB float (relying on casting) or whether to (2b) keep run_number, rerun_number as DB ints (relying on composing/decomposing abstract properties with getter/setter).

**Comment by tiborsimko** [comment]
(3) Warn user that workflow does not correspond to asked-for rerun number, for example if there were thirtheen reruns of `myanalysis.42`, and if a user ask for some intermediate one:

```console
$ reana-client ls -w myanalysis.42.7
[WARNING] Showing latest workspace `myanalysis.42` corresponding to the latest rerun number `myanalysis.42.13`:
...
```
