### ISSUE TITLE
db: REANA database gets deleted when cluster is restarted (PostgreSQL pod)

### ISSUE THREAD

**Issue by anton-khodak** [reanahub/reana-workflow-controller#52]
Undesired behavior if a user wants to stop cluster or a development machine for a while

**Comment by tiborsimko** [comment]
Personally I am just suspending the VM when I'm not working on REANA, and resuming the same VM when I get back to working on REANA. Alternatively, you could also mount a local laptop folder into the minikube using `minikube mount` and use even hard delete/create cycle instead of the above suspend/resume cycle. Would these techniques address the original problem?

**Comment by anton-khodak** [comment]
By suspending you mean `minikube stop && minikube start` or...?

Yes, mounts would solve the problem, however, having a configuration to prevent analyses being erased after `minikube stop`, if feasible, would be more user-friendly.

Anyway, if the question of data persistence is solved in some other way in the production environment, this can be closed.

**Comment by tiborsimko** [comment]
I'm not suspending via `minikube` CLI, but via Hypervisor CLI tools, for example:

```console
$ sudo virsh suspend minikube
$ # work on something else
$ sudo virsh resume minikube
```

The same can be achieved in VirtualBox GUI.

We should document this; moving the milestone.

**Comment by diegodelemos** [comment]
Title updated since this is now happening because the database disappears with the PostgreSQL pod. We should use persistent volume for `/var/lib/postgresql/data`.
