### ISSUE TITLE
Error: No such command "users".

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-controller#64]
Seen with latest `master`:

```console
$ kubectl get pods | grep workflow-controller
workflow-controller-2663988704-cp41b     0/1       CrashLoopBackOff   6          12m

$ kubectl logs workflow-controller-2663988704-cp41b
/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "users".
```

**Comment by tiborsimko** [comment]
Interestingly, the `flask users` command was not available when the current working directory was `/code`, but it was available elsewhere, e.g. in `/`.  This turned out to be due to old pyc/eggs lying in the directory that was mounted in during docker build.  

(1) We should exclude these during build e.g. via `.dockerignore` in the future.

(2) A quick fix for the moment is to clean up these locally:

```console
$ cd reana-<component>
$ find . -name "*.pyc" -delete
$ find . -type d -name "*.egg-info" -exec rm -rf {} \;
$ find . -type d -name ".eggs" -exec rm -rf {} \;
$ find . -type d -name __pycache__ -delete
``` 

before building the images.

**Comment by hjhsalo** [comment]
Need to reopen this since it was discovered that `users` command in reana-workflow-controller, won't work if:
1. Deploy a development cluster with latest master-branch code according to http://reana-cluster.readthedocs.io/en/latest/developerguide.html#deploying-latest-master-branch-versions 
2. **DON'T RUN** `pip install -e .` in `reana-workflow-controller` source folder.
3. Mount the source folder with `minikube mount` and overwrite `/code` inside REANA-Workflow-Controller Pod.

Fix:
**This problem is easily fixable by running `pip install -e .` inside REANA-Workflow-Controller source code directory on the computer/host where you have cloned REANA-Workflow-Controller repository.**

Explanation / speculation:
What seems to be happening is that the shell mapping for `reana-workflow-controller users` command is not getting created / registered unless you at least once install REANA-Workflow-Controller by running `pip install -e .` inside the source directory you are editing.
I'm by no means a setuptools specialist, but maybe the thing is that without running `pip install -e .` no `reana-workflow-controller` -eggs are created, and because `minikube mount` + `hostPath`-mappings in `reana-cluster-dev.yaml` overwrite the whole folder (including the setuptools eggs) in REANA-Workflow-Controller Pod, `reana-workflow-controller users` doesn't exist inside REANA-Workflow-Controller Pod after `minikube mount`

Please note that currently `pip` command is not available inside REANA-Workflow-Controller Pod, so you actually need to do `pip install -e .` on the machine/host where you have `pip` available.

**Comment by diegodelemos** [comment]
Closing as this doesn't happen anymore in RWC. In any case, if this happens again we know how to fix it, see the fix for REANA-Server at https://github.com/reanahub/reana/pull/198.
